---
# tasks file for web

- name: Install Nginx
  apt:
    pkg: 
    - nginx
    - zip
    - unzip

- name: Install nodejs & npm
  apt:
    pkg:
      - nodejs
      - npm

- name: Install PHP-FPM
  apt: 
    pkg: 
       - "php{{ php_version }}"
       - "php{{ php_version }}-apcu"
       - "php{{ php_version }}-cli"
       - "php{{ php_version }}-common"
       - "php{{ php_version }}-curl"
       - "php{{ php_version }}-dev"
       - "php{{ php_version }}-fpm"
       - "php{{ php_version }}-gd"
       - "php{{ php_version }}-imap"
       - "php{{ php_version }}-json"
       - "php{{ php_version }}-mbstring"
       - "php{{ php_version }}-opcache"
       - "php{{ php_version }}-sqlite3"
       - "php{{ php_version }}-xml"
       - "php{{ php_version }}-yaml"
       - "php{{ php_version }}-zip"
       - "php{{ php_version }}-mysql"

- name: Configure php.ini
  blockinfile:
    path: /etc/php/{{ php_version }}/fpm/php.ini
    block: |
      date.time = {{ php_date_timezone }}
    backup: yes
  notify: 
    - restart php-fpm

- name: Create Nginx virtual host
  template:
    src: virtual_host.j2
    dest: /etc/nginx/sites-enabled/{{ domain_name }}.conf
  notify: 
   - restart nginx

- name: Create web root directory
  file:
    path: /var/www/{{ domain_name }}
    state: directory

- name: Upload index.php file to web root directory
  template: 
    src: index.php.j2
    dest: /var/www/{{ domain_name }}/index.php

- name: Allow Nginx HTTP
  ufw:
   rule: allow
   name: "Nginx HTTP"

- name: Download composer
  get_url:
      dest: "{{ composer.installer }}" # required. Absolute path of where to download the file to.,If C(dest) is a directory, either the server provided filename or, if none provided, the base name of the URL on the remote server will be used. If a directory, C(force) has no effect.,If C(dest) is a directory, the file will always be downloaded (regardless of the C(force) option), but replaced only if the contents changed..
      url: "https://getcomposer.org/installer" # required. HTTP, HTTPS, or FTP URL in the form (http|https|ftp)://[user[:pass]]@host.domain[:port]/path
  tags:
  - composer

- name: Install composers
  command: "{{ item }}"
  with_items:
    - "php {{ composer.installer }}"
    - mv composer.phar /usr/local/bin/composer
  tags:
    - composer  

- name: Remove composer installer
  file:
    path: "{{ composer.installer }}"
    state: absent
  tags:
    - composer   

- name: Print composer version
  command: composer -v
  register: version
- debug: msg="{{ version.stdout_lines }}"
